# Generated by Django 4.1.7 on 2023-02-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'قيد التنفيذ'), (2, 'مكتمل'), (3, 'معلق'), (4, 'ملغي')], default=1),
        ),
    ]
